### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by janrinze** [joshajohnson/iCE40-feather#2]
Out of curiosity, is there a production run of these boards?
How would I obtain one?

Best regards,
Jan Rinze.

**Comment by Riconec** [comment]
I ordered my on oshpark and soldered by hand, just used pcb files from repo.

**Comment by joshajohnson** [comment]
Sorry for the (uselessly) late reply @janrinze, only just saw this...
I did a small production run for some friends, but don't have any left.
Best bet would to assemble your own, any questions please get in touch.
