### ISSUE TITLE
Pins 20-23 not in 2.54 grid

### ISSUE THREAD

**Issue by Riconec** [joshajohnson/iCE40-feather#3]
I am trying to solder "feather wing" based on perfboard with 2.54 grid. And I noticed that bottom pads with GPIO not in that grid, so pogo pins need to be **very** precisely alligned (broke more than actually soldered in process).

**May be** it would be nice tomove it a bit if you are planning to make new boards.

Not complaining or else, just my observations that may be usefull (or not :) )

P.S. thanks for the board

**Comment by joshajohnson** [comment]
Hey @Riconec, sorry the very very late reply, only just saw this... 
I am aware of this, unfortunately due to the density of the board it was either have them off grid or not at all. I spent far too long attempting to make them fit on grid...
